"""ORM model for intelligence alerts delivered to publishers.

Alerts are generated by the MMIP scoring engine and Celery tasks when
significant market events are detected. Each alert carries a required_tier
field that gates visibility based on the publisher's subscription level.
"""

import enum
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, Enum, ForeignKey, Index, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.publisher import Publisher
    from app.models.title import Title


class AlertType(str, enum.Enum):
    """Category of market intelligence signal represented by the alert."""

    BREAKOUT = "BREAKOUT"
    GENRE_TREND = "GENRE_TREND"
    ANIME_IMPACT = "ANIME_IMPACT"
    OVERSEAS_DEMAND = "OVERSEAS_DEMAND"
    COMPETITOR_MOVEMENT = "COMPETITOR_MOVEMENT"


class AlertSeverity(str, enum.Enum):
    """Urgency level of the alert for triage and notification routing."""

    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertRequiredTier(str, enum.Enum):
    """Minimum publisher subscription tier required to view this alert."""

    BASIC = "BASIC"
    PRO = "PRO"
    ENTERPRISE = "ENTERPRISE"


class Alert(BaseModel):
    """An intelligence alert notifying a publisher of a market event.

    Attributes:
        id: Auto-incrementing primary key.
        publisher_id: Foreign key referencing the target publisher.
        title_id: Optional FK referencing the title the alert concerns.
            Null for publisher-wide or genre-level alerts.
        alert_type: Classification of the market signal.
        severity: Urgency classification for routing and display.
        message: Human-readable summary of the alert event.
        data: Optional structured JSON payload with supporting metrics.
        is_read: Whether the publisher has acknowledged the alert.
        required_tier: Minimum subscription level required to see the alert.
        created_at: Row creation timestamp.
        updated_at: Row last-modified timestamp.
        publisher: Many-to-one relationship to the receiving Publisher.
        title: Optional many-to-one relationship to the referenced Title.
    """

    __tablename__ = "alerts"

    publisher_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("publishers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("titles.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    alert_type: Mapped[AlertType] = mapped_column(
        Enum(AlertType, name="alert_type"),
        nullable=False,
        index=True,
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity"),
        nullable=False,
        default=AlertSeverity.INFO,
        index=True,
    )
    message: Mapped[str] = mapped_column(Text, nullable=False)
    data: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    required_tier: Mapped[AlertRequiredTier] = mapped_column(
        Enum(AlertRequiredTier, name="alert_required_tier"),
        nullable=False,
        default=AlertRequiredTier.BASIC,
    )

    # Relationships
    publisher: Mapped["Publisher"] = relationship(
        "Publisher", back_populates="alerts", lazy="select"
    )
    title: Mapped["Title | None"] = relationship(
        "Title", back_populates="alerts", lazy="select"
    )

    __table_args__ = (
        Index("ix_alerts_publisher_is_read", "publisher_id", "is_read"),
        Index("ix_alerts_publisher_severity", "publisher_id", "severity"),
        Index("ix_alerts_publisher_type", "publisher_id", "alert_type"),
        Index("ix_alerts_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<Alert id={self.id} type={self.alert_type} "
            f"severity={self.severity} is_read={self.is_read}>"
        )
